# Generated by Django 3.2.4 on 2021-08-12 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='nama',
            new_name='name',
        ),
    ]
